### ISSUE TITLE
一个bug好像，不知道在哪里问了，

### ISSUE THREAD

**Issue by 6923403** [nft-rainbow/rainbow-dashboard#74]
创建了一个POAP给群里发点藏品，创建好之后项目管理打不开，藏品正常发放，

然后我又新建了一个POAP，新建的这个POAP项目管理正常打开

错误项目， https://console.nftrainbow.cn/panels/poaps/7cbceb1a/updateGasless

![image](https://github.com/nft-rainbow/rainbow-dashboard/assets/39010651/9e42904d-3f79-4b84-a4a6-dd2789dc5117)

**Comment by Pana** [comment]
收到，我们看下

**Comment by 6923403** [comment]
> 我们看下

你好，不知道找到问题没有， 我这边现在还是老样子

**Comment by Pana** [comment]
我们这边试了下是正常的，能提供下详细的复现步骤跟环境说明么

**Comment by 6923403** [comment]
> 我们这边试了下是正常的，能提供下详细的复现步骤跟环境说明么

macos13.4,chrome版本 114.0.5735.133

NFT活动类， 创建poap项目，创建成功之后，通过机器人在dodo频道领取，然后就打不开了

你可以留个邮箱，我把账号发给你，登陆试一下
